### ISSUE TITLE
Integration of fingerprint sensor to Raspberry Pi

### ISSUE THREAD

**Issue by ashwinhr186** [ashwinhr186/aesd-final-project-vidhya-ashwin#1]
DoD: Verification of successful read from fingerprint sensor
Blockers: Availability of fingerprint sensor

**Comment by vidhyapalaniappan** [comment]
Blocker :  Currently blocked due to the unavailability of fingerprint sensor (Expected to arrive on 11/21/2023)

**Comment by ashwinhr186** [comment]
Update as on 3rd December, 2023:

Integration of Fingerprint sensor to RPi through USB done
Built the image including the fingerprint related code and packages/dependencies
Successfully verified the functionality of fingerprint sensor on RPi using built image

DoD achieved and verified
Blockers: none

**Comment by vidhyapalaniappan** [comment]
![Image](https://github.com/ashwinhr186/aesd-final-project-vidhya-ashwin/assets/111988668/f1934896-35de-4e03-bc08-9a72a1d74c0c)

- Able to enroll a new finger print.
- Able to compare the fingerprint with existing database
- Able to delete the fingerprint data

**Comment by ashwinhr186** [comment]
Adding link to the issue: https://github.com/cu-ecen-aeld/final-project-vidhyapalaniappan/commit/e430d35c1156811cffac68da97d03627597ceeb5
