### ISSUE TITLE
Bring up Raspberry Pi using the build from buildroot

### ISSUE THREAD

**Issue by ashwinhr186** [ashwinhr186/aesd-final-project-vidhya-ashwin#4]
DoD: using the build/image from buildroot, port it on Raspberry Pi and bring up the board. 

Blockers: None

**Comment by vidhyapalaniappan** [comment]
- Tested the custom build kernel image on rpi 
- Were able to see the boot up logs
- Were able to see the devices connected to rpi
- Logged in as root
- When did cd/urs/bin were able to see the basic applications 

DoD was verified successfully and no blockers we observed.

![Image](https://github.com/ashwinhr186/aesd-final-project-vidhya-ashwin/assets/111988668/21efe3d5-990f-4d1d-973b-dfa3e2e11c21)
