### ISSUE TITLE
Integration of LCD with Raspberry Pi

### ISSUE THREAD

**Issue by ashwinhr186** [ashwinhr186/aesd-final-project-vidhya-ashwin#6]
DoD: Ensuring successful integration of LCD into Raspberry Pi and verifying the display output to be appropriate.
Blockers: procurement of LCD

**Comment by vidhyapalaniappan** [comment]
Update: Currently no blocker as LCD was procured.

**Comment by vidhyapalaniappan** [comment]
- Developed code to interface LCD with Rpi.
- Initialized the necessary gpio modules
- Added the gpio package in buildroot and built the image
- Made the necessary hardware connections between Rpi and LCD
- Tested the image
- Were able to see the test string being displayed on LCD

DoD was verified successfully and no blockers we observed




![Image](https://github.com/ashwinhr186/aesd-final-project-vidhya-ashwin/assets/111988668/63eeda12-ab92-4b0a-865b-821352b09961)



![Image](https://github.com/ashwinhr186/aesd-final-project-vidhya-ashwin/assets/111988668/cc6c4dbc-5b42-4e3b-b76c-32e6df3e4123)

**Comment by vidhyapalaniappan** [comment]
adding just the link to code commit : https://github.com/cu-ecen-aeld/final-project-vidhyapalaniappan/commit/cfd460f2776f70587fc26b623d8df03e174a9c83
