### ISSUE TITLE
Final Build

### ISSUE THREAD

**Issue by ashwinhr186** [ashwinhr186/aesd-final-project-vidhya-ashwin#8]
DoD: Build the image to include all the functionalities and port into Raspberry Pi using buildroot
Blockers: None

**Comment by vidhyapalaniappan** [comment]
- Developed code to interface numpad, fingerprint and LCD modules together
- The numpad and fingerprint programs were in python whereas the lcd program was in C code
- Used subprocess API to call LCD function in numpad and fingerprint
- Added the necessary packages in buildroot
- Made hardware connections for all three modules in rpi
- Tested the image
- Were able to see the the expected authentication success or failure message on LCD

DoD was verified successfully and no blockers we observed

link to code commit : https://github.com/cu-ecen-aeld/final-project-vidhyapalaniappan/commit/186216f2c9b30911d1acb2e69f5fdef436ef0a98



![Image](https://github.com/ashwinhr186/aesd-final-project-vidhya-ashwin/assets/111988668/52e31d8b-de86-4b55-b3fc-855783a7ec8b)
