### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ashwinhr186** [ashwinhr186/aesd-final-project-vidhya-ashwin#9]
DoD: document readme.md, demo video and necessary files
Blockers: none

**Comment by ashwinhr186** [comment]
Update as of 10th December, 2023:

Completed readme,md
Demo video is work in progress
Documentation for extra credit is in progress

**Comment by vidhyapalaniappan** [comment]
Completed readme.md
Demo video recorded
Documentation for extra credit is completed
